### ISSUE TITLE
Can't get this working for .html.erb files

### ISSUE THREAD

**Issue by brandoncordell** [PriceHiller/nvim-ts-autotag#2]
I followed the README instructions, at least as far as I can tell.

```lua
return {
  {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    dependencies = {
      'RRethy/nvim-treesitter-endwise',
      'PriceHiller/nvim-ts-autotag', -- installed further down in the plugins file
    },
    config = function()
      local configs = require('nvim-treesitter.configs')

      configs.setup({
        autotag = { enable = true },
        endwise = { enable = true },
        ensure_installed = { 'c', 'lua', 'vim', 'vimdoc', 'query', 'elixir', 'javascript', 'html', 'ruby', 'typescript' },
        highlight = { enable = true },
        indent = { enable = true },
      })
    end
  },

  -- ...
}
```

`Lazy` shows the plugin is loaded when I'm in a `.html.erb` file but neither the autoclose or tag replacement works.

**Comment by PriceHiller** [comment]
Instead of using nvim-treesitter's setup function, try doing `require("nvim-ts-autotag").setup()` instead. I'm still working around some of the internals of this plugin and I suspect that's causing the majority of folk's issues.

If that doesn't work then can you try cloning the plugin and use the `minimal_init.lua` file at `tests/minimal_init.lua` then edit the `.html.erb` file at `sample/index.html.erb`?

You can run the following:

```
git clone https://github.com/PriceHiller/nvim-ts-autotag/ autotag
cd autotag
nvim -nu tests/minimal_init.lua sample/index.html.erb
```

**Comment by PriceHiller** [comment]
Checking in with you @brandoncordell, did you ever get this working/try to do the alternative setup?

**Comment by PriceHiller** [comment]
I'm going to assume all is good on your side and close this issue. Please re-open a new one if you're still facing problems 🙂
